[package]
name = "loz"
version = "0.1.0"
authors = ["Haye BÃ¶hm <haye.bohm@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.1.2"
pest_derive = "2.1.0"
